# Generated by Django 5.1.5 on 2025-05-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('old_job', models.CharField(blank=True, null=True, verbose_name='Пред. работа')),
                ('new_job', models.CharField(blank=True, null=True, verbose_name='Новая. работа')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(verbose_name='Номер страницы')),
                ('title', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('cards', models.ManyToManyField(blank=True, null=True, related_name='content', to='main.cards', verbose_name='Карточки')),
            ],
        ),
        migrations.CreateModel(
            name='Curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название курса')),
                ('page_and_content', models.ManyToManyField(blank=True, null=True, related_name='curs', to='main.content', verbose_name='Страница и контент')),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card', to='main.image'),
        ),
    ]
