# Generated by Django 5.1.5 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название курса')),
                ('page_and_content', models.ManyToManyField(blank=True, null=True, related_name='course', to='main.content', verbose_name='Страница и контент')),
            ],
        ),
        migrations.DeleteModel(
            name='Curs',
        ),
    ]
