# Generated by Django 5.1.5 on 2025-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_сourse_delete_curs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cards',
            new_name='Card',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(),
        ),
    ]
