# Generated by Django 5.1.5 on 2025-05-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_card_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Стоимость курса', editable=False)),
                ('full_price', models.IntegerField(verbose_name='Полная стоимость')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('month', models.IntegerField(verbose_name='Месяцев')),
            ],
            options={
                'verbose_name': 'Страница 22',
                'verbose_name_plural': 'Страницы 22',
            },
        ),
        migrations.CreateModel(
            name='Page5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Сколько ты хотел(а) б зарабатывать, чтобы удовлетворить свои потребности?', editable=False)),
                ('price1', models.IntegerField(verbose_name='Первая цена')),
                ('price2', models.IntegerField(verbose_name='Вторая цена')),
                ('price3', models.IntegerField(verbose_name='Третья цена')),
            ],
            options={
                'verbose_name': 'Страница 5',
                'verbose_name_plural': 'Страницы 5',
            },
        ),
        migrations.CreateModel(
            name='Page6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Насколько ты согласен(на) со следующим утверждением:', editable=False)),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница 6',
                'verbose_name_plural': 'Страницы 6',
            },
        ),
        migrations.RemoveField(
            model_name='content',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='сourse',
            name='page_and_content',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AddField(
            model_name='сourse',
            name='direction',
            field=models.CharField(blank=True, null=True, verbose_name='Под направление'),
        ),
        migrations.AddField(
            model_name='сourse',
            name='url_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для копирования'),
        ),
        migrations.CreateModel(
            name='CardForPage13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('description', models.CharField(verbose_name='Описание навыка')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image', verbose_name='Фото навыка ')),
            ],
            options={
                'verbose_name': 'Карточка для страница 13',
                'verbose_name_plural': 'Карточки для страница 13',
            },
        ),
        migrations.CreateModel(
            name='CardForPage14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('description', models.CharField(verbose_name='Имя Фамилия')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Карточка для страница 14',
                'verbose_name_plural': 'Карточки для страница 14',
            },
        ),
        migrations.CreateModel(
            name='CardForPage15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('description', models.CharField(verbose_name='Описание')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Карточка для страница 15',
                'verbose_name_plural': 'Карточки для страница 15',
            },
        ),
        migrations.CreateModel(
            name='CardForPage16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('description', models.CharField(verbose_name='Описание')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Карточка для страница 15',
                'verbose_name_plural': 'Карточки для страница 15',
            },
        ),
        migrations.CreateModel(
            name='CardForPage8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Отзыв студента ')),
                ('old_job', models.CharField(verbose_name='Предыдущее место работы ')),
                ('new_job', models.CharField(verbose_name='Новое место работы ')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.image', verbose_name='Фото студета ')),
            ],
            options={
                'verbose_name': 'Карточка для страница 8',
                'verbose_name_plural': 'Карточки для страница 8',
            },
        ),
        migrations.CreateModel(
            name='Page11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Как думаешь, какими бы вышли твои дизайны, начни ты прямо сейчас?', editable=False)),
                ('head', models.TextField(verbose_name='Заголовок')),
                ('collect_image', models.ManyToManyField(related_name='page11', to='main.image', verbose_name='Коллеция Фото')),
            ],
            options={
                'verbose_name': 'Страница 11',
                'verbose_name_plural': 'Страницы 11',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page11', to='main.page11', verbose_name='Страница 11'),
        ),
        migrations.CreateModel(
            name='Page13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Какие навыки ты бы хотел(а) освоить за прохождение курса?', editable=False)),
                ('cards', models.ManyToManyField(related_name='page13', to='main.cardforpage13', verbose_name='Коллеция Навыков')),
            ],
            options={
                'verbose_name': 'Страница 13',
                'verbose_name_plural': 'Страницы 13',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page13', to='main.page13', verbose_name='Страница 13'),
        ),
        migrations.CreateModel(
            name='Page14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Вот какого результата добились студенты курса', editable=False)),
                ('cards', models.ManyToManyField(related_name='page14', to='main.cardforpage14', verbose_name='Коллеция Карточек')),
            ],
            options={
                'verbose_name': 'Страница 14',
                'verbose_name_plural': 'Страницы 14',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page14', to='main.page14', verbose_name='Страница 14'),
        ),
        migrations.CreateModel(
            name='Page15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Что привлекает в курсе?', editable=False)),
                ('cards', models.ManyToManyField(related_name='page15', to='main.cardforpage15', verbose_name='Коллеция Карточек')),
            ],
            options={
                'verbose_name': 'Страница 15',
                'verbose_name_plural': 'Страницы 15',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page15',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page15', to='main.page15', verbose_name='Страница 15'),
        ),
        migrations.CreateModel(
            name='Page16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='Что привлекает в курсе?', editable=False)),
                ('head', models.TextField(verbose_name='Заголовок')),
                ('cards', models.ManyToManyField(related_name='page16', to='main.cardforpage16', verbose_name='Коллеция Карточек')),
            ],
            options={
                'verbose_name': 'Страница 16',
                'verbose_name_plural': 'Страницы 16',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page16',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page16', to='main.page16', verbose_name='Страница 16'),
        ),
        migrations.AddField(
            model_name='сourse',
            name='page22',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page22', to='main.page22', verbose_name='Страница 22'),
        ),
        migrations.AddField(
            model_name='сourse',
            name='page5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page5', to='main.page5', verbose_name='Страница 5'),
        ),
        migrations.AddField(
            model_name='сourse',
            name='page6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page6', to='main.page6', verbose_name='Страница 6'),
        ),
        migrations.CreateModel(
            name='Page8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(verbose_name='Название курса')),
                ('title', models.TextField(default='У 106+ тысяч студентов уже получилось, а значит и ты сможешь изменить свою жизнь в лучшую сторону!', editable=False)),
                ('cards', models.ManyToManyField(blank=True, null=True, related_name='page8', to='main.cardforpage8', verbose_name='Карточки')),
            ],
            options={
                'verbose_name': 'Страница 8',
                'verbose_name_plural': 'Страницы 8',
            },
        ),
        migrations.AddField(
            model_name='сourse',
            name='page8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page8', to='main.page8', verbose_name='Страница 8'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
