# Generated by Django 5.1.5 on 2025-05-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_page22_page5_page6_remove_content_cards_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сourse',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
    ]
